# Generated by Django 5.2 on 2025-08-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_alter_tourpackage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=50)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travello.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
