# Generated by Django 5.2 on 2025-08-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_travelhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelhistory',
            name='points_awarded',
        ),
    ]
